(define (domain school)
    (:requirements :strips)
    (:predicates (is_agent ?x) (is_bin ?x)(agent_at ?x ?y) (bin_at ?x ?y)(adj ?x ?y) (throw_in_bin ?x))
    (:functions (level ?x))
    (:action move
        :parameters (?r ?from ?to)
        :effect (and (not(at ?r ?from)) (at ?r ?to))
        :precondition (and (is_agent ?r) (agent_at ?r ?from) (adj ?from ?to) )
    )
    (:action recycle
        :parameters (?r ?b ?pos)
        :effect (and (throw_in_bin ?b))
        :precondition (and (is_agent ?r) (is_bin ?b) (agent_at ?r ?pos) (bin_at ?b ?pos) (< (level ?b) 3))
    )
)